# Generated by Django 4.2.16 on 2025-12-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام نرم\u200cافزار')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('cover_image', models.ImageField(upload_to='software_covers/', verbose_name='تصویر کاور')),
                ('developer', models.CharField(max_length=100, verbose_name='سازنده')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('installation_guide', models.TextField(blank=True, verbose_name='راهنمای نصب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='software.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'نرم\u200cافزار',
                'verbose_name_plural': 'نرم\u200cافزارها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='نسخه')),
                ('platform', models.CharField(choices=[('win', 'Windows'), ('mac', 'macOS'), ('linux', 'Linux'), ('android', 'Android')], max_length=10, verbose_name='پلتفرم')),
                ('specific_install_guide', models.TextField(blank=True, verbose_name='راهنمای نصب اختصاصی این نسخه')),
                ('is_active', models.BooleanField(default=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='software.software')),
            ],
            options={
                'verbose_name': 'نسخه/ریلیز',
                'verbose_name_plural': 'نسخه\u200cها',
                'unique_together': {('software', 'version', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='software',
            name='tags',
            field=models.ManyToManyField(blank=True, to='software.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.CreateModel(
            name='FilePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveSmallIntegerField(default=1, verbose_name='شماره پارت')),
                ('download_link', models.URLField(max_length=500, verbose_name='لینک دانلود')),
                ('file_size', models.CharField(help_text='مثال: 2 GB', max_length=50, verbose_name='حجم')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='software.softwarerelease')),
            ],
            options={
                'verbose_name': 'پارت دانلود',
                'verbose_name_plural': 'پارت\u200cهای دانلود',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='ویژگی')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='software.software')),
            ],
        ),
    ]
